export const ADD_STEPS_STARTED = "ADD_STEPS_STARTED";
export const ADD_STEPS_COMPLETED = "ADD_STEPS_COMPLETED";
export const ADD_STEPS_FAILED = "ADD_STEPS_FAILED";
export const ADD_SELECTED_DAY = "ADD_SELECTED_DAY";
